// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {db} from '../models';

export function CreateServer(arg1:Record<string, any>):Promise<utils.Response>;

export function DeleteServer(arg1:number):Promise<void>;

export function GetAllServers():Promise<Array<db.Server>>;

export function GetServerByID(arg1:number):Promise<db.Server>;

export function Greet(arg1:string):Promise<string>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer(arg1:number):Promise<void>;

export function UpdateServer(arg1:Record<string, any>):Promise<void>;
