// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1:Record<string, any>):Promise<void>;

export function Greet(arg1:string):Promise<string>;
